#!/bin/bash
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2015 Volker Theile
# @copyright Copyright (c) 2015-2017 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://linux.die.net/man/8/cryptsetup
# http://linux.die.net/man/5/crypttab
# https://gitlab.com/cryptsetup/cryptsetup

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_LUKS_CRYPTDISKS_DEFAULT=${OMV_LUKS_CRYPTDISKS_DEFAULT:-"/etc/default/cryptdisks"}
OMV_LUKS_CRYPTTAB_CONFIG=${OMV_LUKS_CRYPTTAB_CONFIG:-"/etc/crypttab"}
OMV_SF_DM="conf.system.sharedfolder"
OMV_LUKS_DM="conf.service.luks"
OMV_LUKS_DEVICE_DM="conf.service.luks.device"
OMV_FSTAB_MNTENT_DM="conf.system.filesystem.mountpoint"
OMV_LUKS_DECRYPT_TARGET="/etc/systemd/system/decrypt.target"
OMV_LUKS_POST_DECRYPT_TARGET="/etc/systemd/system/post-decrypt.target"
OMV_LUKS_STARTFULLSYSTEMD_TARGET="/etc/systemd/system/final-decrypt.target"
OMV_LUKS_SYSTEMD_UNIT_PREFIX="/etc/systemd/system/openmediavault-luks-"


_generate_decrypt_target ()
{
	cat << EOF > ${OMV_LUKS_DECRYPT_TARGET}
[Unit]
Description=Decrypted System
Documentation=https://blog.iwakd.de/headless-luks-decryption-via-ssh
Requires=before-decrypt.target
After=before-decrypt.target
Before=zfs.target
Conflicts=systemd-ask-password-console.path systemd-ask-password-console.service systemd-ask-password-plymouth.path systemd-ask-password-plymouth.service
EOF
	
### Get all cryptodevices in crypttab and put them in the decrypt target as dependancy
	for i in ${omv_luks_crypttab_devices[@]};do
		echo "Requires=systemd-cryptsetup@`systemd-escape --suffix "service" --path $i`" >> "${OMV_LUKS_DECRYPT_TARGET}"
	done
}

### Is necessary to split into two targets, one to handle device unlocking and the other one to handle mounts. This is in case
### a crypto device is a zfs member
_generate_postdecrypt_target ()
{
		cat << EOF > ${OMV_LUKS_POST_DECRYPT_TARGET}
[Unit]
Description=Mount decrypted and unencrypted drives
Documentation=https://blog.iwakd.de/headless-luks-decryption-via-ssh
Requires=decrypt.target
After=decrypt.target
EOF

### Get all openmediavault fstab mount points and put them in the decrypt target as dependancy
	for i in ${omv_systemd_mnt_points[@]};do
		echo "Requires=`systemd-escape --suffix "mount" --path $i`" >> "${OMV_LUKS_POST_DECRYPT_TARGET}"
	done

### Get all sharedfolder systemd bind mount units, disable them and add them to the decrypt target as dependancy
	for name in ${sf_names[@]};do
		sf_unit="sharedfolders-"`systemd-escape --suffix "mount" --path $name`
		# systemctl disable "${sf_unit}"
		echo "Requires=${sf_unit}" >> "${OMV_LUKS_POST_DECRYPT_TARGET}"
	done

}

_generate_startfullsystemd_target () 
{
		cat << EOF > ${OMV_LUKS_STARTFULLSYSTEMD_TARGET}
[Unit]
Description=Start full multi-user.target
Documentation=https://blog.iwakd.de/headless-luks-decryption-via-ssh
Requires=post-decrypt.target
After=post-decrypt.target
EOF
	echo "Requires=omv-luks-start-full-systemd.service" >> "${OMV_LUKS_STARTFULLSYSTEMD_TARGET}"

}

_clean_luks_systemd_units ()
{
	if test -n "$(find /etc/systemd/system -maxdepth 1 -name 'openmediavault-luks-*' -print -quit)";then
		find /etc/systemd/system -maxdepth 1 -name 'openmediavault-luks-*' -execdir rm -rf {} ";"
		rm -fr /etc/systemd/system/openmediavault-luks-*.service
	fi
}


_generate_automount_systemd_unit () 
{
	luks_settings_enable_keydevice=$(omv-confdbadm read ${OMV_LUKS_DM} | jq -r '.|.enablekeydevice')
	luks_settings_keydevice_encrypted=$(omv-confdbadm read ${OMV_LUKS_DM} | jq -r '.|.isencrypted')

	if [ "${luks_settings_enable_keydevice}" == "true" ] && [ "${luks_settings_keydevice_encrypted}" == "false" ];then
	# echo "YES"
	_clean_luks_systemd_units
	luks_settings_keydevice_uuid=$(omv-confdbadm read ${OMV_LUKS_DM} | jq -r '.|.uuid')
	luks_settings_keydevice_predictable=$(omv-confdbadm read ${OMV_LUKS_DM} | jq -r '.|.predictable')
	unitfile="${OMV_LUKS_SYSTEMD_UNIT_PREFIX}""${luks_settings_keydevice_uuid//-/}".service
	devicefile=$(systemd-escape --suffix "device" --path ${luks_settings_keydevice_predictable})

	cat << EOF > ${unitfile}
[Unit]
Description=Auto run script
BindsTo=${devicefile}
After=${devicefile}
Requisite=${devicefile}

[Service]
Type=oneshot
RemainAfterExit=false
ExecStart=/usr/sbin/omv-luks-start

[Install]
WantedBy=${devicefile}
EOF
	systemctl enable ${unitfile}
	fi
}

sf_all=$(omv-confdbadm read ${OMV_SF_DM})
sf_names=( $(echo ${sf_all} | jq -r '.[]|.name') )
luks_settings_enable=$(omv-confdbadm read ${OMV_LUKS_DM} | jq -r '.|.enable')

case "${luks_settings_enable}" in
	"true")
		omv_systemd_mnt_points=( $(omv-confdbadm read --prettify ${OMV_FSTAB_MNTENT_DM} | 
                                                        jq -r '.[]| 
                                                        	   select(.type!="zfs")|
                                                        	   .dir') )
		omv_luks_crypttab_devices=( $(omv-confdbadm read ${OMV_LUKS_DEVICE_DM} |
														jq -r '.[] |
															   .name' ) )
		_generate_decrypt_target
		_generate_postdecrypt_target
		_generate_startfullsystemd_target
		_generate_automount_systemd_unit		
		systemctl set-default before-decrypt.target
		;;
	"false")
		if [ -f ${OMV_LUKS_DECRYPT_TARGET} ]; then
			rm -rf ${OMV_LUKS_DECRYPT_TARGET}
		fi
		for name in ${sf_names[@]};do
			sf_unit="sharedfolders-"`systemd-escape --suffix "mount" --path $name`
			systemctl enable "${sf_unit}"
		done
		_clean_luks_systemd_units
		systemctl set-default graphical.target
		;;
esac


