#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        XPATH="/config/system/notification/notifications"

        if ! omv_config_exists "${XPATH}/notification[id='luks']"; then
            object="<uuid>$(omv_uuid)</uuid>"
            object="${object}<id>luks</id>"
            object="${object}<enable>0</enable>"
            omv_config_add_node_data "${XPATH}" "notification" "${object}"
        fi

        SERVICE_XPATH_NAME="luks"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"


        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_node "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_key "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_key "${SERVICE_XPATH}" "devicefile" ""
            omv_config_add_key "${SERVICE_XPATH}" "uuid" ""
            omv_config_add_key "${SERVICE_XPATH}" "isencrypted" ""
            omv_config_add_key "${SERVICE_XPATH}" "description" ""
            omv_config_add_key "${SERVICE_XPATH}" "predictable" ""
            omv_config_add_node "${SERVICE_XPATH}" "crypttab"
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale


    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
